### PR TITLE
update simple logger: 1.9.0 -> 5.0.0

### PR DESCRIPTION
**Pull request by i-am-yuvi**
#3
Can you review this @0xB10C!

### CODE REVIEW

**Review by 0xB10C — APPROVED** [review]
Tested ACK! Thanks.

I verified that simple_logger version 1.9.0 still fails (as reported in #3) and that upgrading to v5.0.0 works. 

With `v1.9.0`:
```
$ cargo run --bin metrics -- -m 127.0.0.1:8382
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/metrics -m '127.0.0.1:8382'`
2024-09-02 11:19:03,084 INFO [main] Starting metrics-server...
thread 'main' panicked at simple_logger-1.16.0/src/lib.rs:409:85:
Could not determine the UTC offset on this system. Possible causes are that the time crate does not implement "local_offset_at" on your system, or that you are running in a multi-threaded environment and the time crate is returning "None" from "local_offset_at" to avoid unsafe behaviour. See the time crate's documentation for more information. (https://time-rs.github.io/internal-api/time/index.html#feature-flags): IndeterminateOffset
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With `v5.0.0`:

```
$ cargo run --bin metrics -- -m 127.0.0.1:8382
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/metrics -m '127.0.0.1:8382'`
2024-09-02T11:23:06.894Z INFO  [main] Starting metrics-server...
2024-09-02T11:23:06.895Z INFO  [metricserver] Started Prometheus metric server listening on 127.0.0.1:8382.
2024-09-02T11:23:06.895Z INFO  [main] metrics-server listening on: 127.0.0.1:8382
```

**Comment by 0xB10C** [comment]
I'm merging this, but there's more work to do on the logging front: https://github.com/0xB10C/peer-observer/issues/46

**Comment by 0xB10C** [comment]
Thanks!
